- app/models/booking.rb
- app/models/service.rb
- app/models/user.rb
- config/routes.rb
- db/migrate/20240120091130_devise_create_users.rb
- db/migrate/20240120091603_create_services.rb
- db/migrate/20240120092251_create_bookings.rb
- db/schema.rb
- test/models/booking_test.rb
- test/models/service_test.rb
- test/models/user_test.rb
service model and booking model also
> User model created

- Gemfile
- Gemfile.lock
- app/models/service.rb
- app/models/user.rb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- db/seeds.rb
- Updated dependecies for the 3 models User, Service & booking
- Updated seed file to use a mix of faker and arrays for categories & cities to be in Japan
[ ] - Pictures are still not used, need to find a way to be able to seed them
> Seed file generation

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_services.scss
- app/controllers/services_controller.rb
- app/views/services/index.html.erb
- config/routes.rb
- test/controllers/services_controller_test.rb
- Made the Services Controller
- Made the index view
- Added some design elements to view to be able to look at
- Added Navbar
- Added H1 Title
- Added Search box
- Added cards for services
> Browse services

- app/controllers/reservations_controller.rb
- app/controllers/services_controller.rb
- app/models/booking.rb
- app/models/service.rb
- app/models/user.rb
- app/views/services/index.html.erb
- app/views/services/show.html.erb
- config.ru
- config/routes.rb
- db/migrate/20240120092251_create_bookings.rb
- test/controllers/reservations_controller_test.rb
Created a Reservation model
Established associations with User and Service
Implemented validations for user ID, service ID, start date, and end date
Added a custom validation ensuring the start date is before the end date
Introduced an enum for reservation status
Integrated the model into the application
Enabled users to make reservations for specific services with date ranges
> Reservation

- app/controllers/reservations_controller.rb
- app/models/user.rb
- app/views/reservations/new.html.erb
- config.ru
- config/routes.rb
- db/migrate/20240120092251_create_bookings.rb
small fix trouble with server error( all fixed)
> fix reservation

- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
Made a home action route through the pages controller 
Also made a basic homepage template with links to the services and bookings index pages
> Made basic homepage

- .vscode/settings.json
- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
changed navber positioning 
make it sticky 
changed dropbox position and removed items we don't need there 
used display none for log In
> changed navbar design

- app/controllers/pages_controller.rb
- Added in pages controller to disable login required
> Removed login required from home page

- app/assets/stylesheets/pages/_services.scss
- app/controllers/bookings_controller.rb
- app/views/services/show.html.erb
- app/views/shared/_booking_form.html.erb
- Booking form is now connected to the user page
- Added some card design in the service show and some designs, will make new design branch
> Connecting service form to booking

- app/assets/stylesheets/pages/_booking_form.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
- I quickly made now a home page for us to be able to start editing
> made a skeleton home page with elements

- app/controllers/services_controller.rb
Edit minor item so that the form will not have a starting value
- Now they all just use placeholders
> Fixed booking form start value

- app/assets/stylesheets/pages/_booking_form.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_services_show.scss
- app/views/services/show.html.erb
- app/views/shared/_booking_form.html.erb
- db/seeds.rb
- adjusted booking bar in service show
- adjusted top half of service-show
> Service#show design

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
just aded few more people on home page looks terrible but no time
> add few cards on home page looks terible but dont have moretime

- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/shared/_footer.html.erb
> fixed empty blanks

- app/models/user.rb
> added owner has many relationship value

- app/views/pages/home.html.erb
- db/schema.rb
> prepared place for services

- app/models/user.rb
- app/views/services/show.html.erb
- db/seeds.rb
The users now all have consistent profile photos which will not change upon reloading the services show page
> updated users seeds with api to include differentiated profile images

- db/seeds.rb
Increased number of users created in seeds to increase the chances of… not having repeated users assigned to the same services
> Added number of user seeds

- app/assets/stylesheets/pages/_services.scss
- app/views/services/index.html.erb
- db/schema.rb
Finished the basics of the services index design.
I made filter buttons which switch the information on the page depending on what is being targeted by the user.
The images are not responsive towards viewpoints because I figured one of you would like to make this look even better.
> Services index design

- app/assets/stylesheets/pages/_services.scss
- app/views/services/index.html.erb
Fixed it by eliminating 'fluid' from the overall container
> fixed the footer of the service index 

- app/assets/stylesheets/pages/_services_show.scss
- app/views/services/show.html.erb
> edited the gallery section of service show page

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_services_show.scss
- app/controllers/reviews_controller.rb
- app/views/reviews/_form.html.erb
- app/views/shared/_navbar.html.erb
fixed issue with reviews and changed black to purple color
> Fixreviews

- app/controllers/bookings_controller.rb
- app/views/shared/_my_services.html.erb
- Iteration working now for dashboard
> Adjusting service display iteration

- app/controllers/services_controller.rb
- app/views/services/edit.html.erb
- app/views/shared/_my_services.html.erb
- created methods for edit, update, destroy
> Services delete edit

- app/assets/stylesheets/pages/_services.scss
- app/assets/stylesheets/pages/_services_show.scss
- app/views/reviews/_form.html.erb
- app/views/shared/_navbar.html.erb
> fixin small visual stuff

- app/assets/stylesheets/pages/_services_show.scss
- app/views/layouts/application.html.erb
- app/views/services/index.html.erb
- app/views/shared/_filter_buttons.html.erb
services index design for carts
> servicescarts

- app/assets/stylesheets/pages/_booking_dashboard.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/shared/_bookings.html.erb
- app/views/shared/_my_services.html.erb
- design button colors and spacing
> Desiging bookings

- app/assets/stylesheets/pages/_services_show.scss
- app/views/services/new.html.erb
- app/views/shared/_new_service.html.erb
> design of create box
